global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: buildstack-api
    metrics_path: /api/core/analytics
    params:
      format: [prometheus]
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/secrets/metrics-scrape-token
    static_configs:
      - targets: ["api:3000"]
